<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\Barangay;
use DB;

class BarangaySeeder extends Seeder {
    public function run()
    {
        // DB::table('barangays')->delete();
        // barangay::create(array('name' => 'Complaint'));
        DB::table('barangays')->delete();
        Barangay::create(array(  "name" => 'ZONE I'));
        Barangay::create(array(  "name" => 'ZONE II'));
        Barangay::create(array(  "name" => 'ZONE III'));
        Barangay::create(array(  "name" => 'ZONE IV'));
        Barangay::create(array(  "name" => 'ARENA BLANCO'));
        Barangay::create(array(  "name" => 'AYALA'));
        Barangay::create(array(  "name" => 'CAMINO NUEVO'));
        Barangay::create(array(  "name" => 'BALIWASAN'));
        Barangay::create(array(  "name" => 'BALUNO'));
        Barangay::create(array(  "name" => 'TUMITUS'));
        Barangay::create(array(  "name" => 'BOALAN'));
        Barangay::create(array(  "name" => 'BOLONG'));
        Barangay::create(array(  "name" => 'BUENAVISTA'));
        Barangay::create(array(  "name" => 'BUNGUIAO'));
        Barangay::create(array(  "name" => 'BUSAY'));
        Barangay::create(array(  "name" => 'CABALUWAY'));
        Barangay::create(array(  "name" => 'CABATANGAN'));
        Barangay::create(array(  "name" => 'CACAO'));
        Barangay::create(array(  "name" => 'CALABASA'));
        Barangay::create(array(  "name" => 'CALARIAN'));
        Barangay::create(array(  "name" => 'CAMPO ISLAM'));
        Barangay::create(array(  "name" => 'CANELAR'));
        Barangay::create(array(  "name" => 'CAPISAN'));
        Barangay::create(array(  "name" => 'CAWIT'));
        Barangay::create(array(  "name" => 'CULIANAN'));
        Barangay::create(array(  "name" => 'CURUAN'));
        Barangay::create(array(  "name" => 'DIVISORIA'));
        Barangay::create(array(  "name" => 'DITA'));
        Barangay::create(array(  "name" => 'DULIAN UPPER BUNGUIAO'));
        Barangay::create(array(  "name" => 'DULIAN UPPER PASONANCA'));
        Barangay::create(array(  "name" => 'GUISAO'));
        Barangay::create(array(  "name" => 'GUIWAN'));
        Barangay::create(array(  "name" => 'LABUAN'));
        Barangay::create(array(  "name" => 'LAMISAHAN'));
        Barangay::create(array(  "name" => 'LANDANG GUA'));
        Barangay::create(array(  "name" => 'LANDANG LAUM'));
        Barangay::create(array(  "name" => 'LANZONES'));
        Barangay::create(array(  "name" => 'LAPACAN'));
        Barangay::create(array(  "name" => 'LA PAZ'));
        Barangay::create(array(  "name" => 'LATUAN'));
        Barangay::create(array(  "name" => 'LIMAONG'));
        Barangay::create(array(  "name" => 'LIMPAPA'));
        Barangay::create(array(  "name" => 'LUBIGAN'));
        Barangay::create(array(  "name" => 'LUMAYANG'));
        Barangay::create(array(  "name" => 'LUMBANGAN'));
        Barangay::create(array(  "name" => 'LUNZURAN'));
        Barangay::create(array(  "name" => 'MAASIN'));
        Barangay::create(array(  "name" => 'MALAGUTAY'));
        Barangay::create(array(  "name" => 'MAMPANG'));
        Barangay::create(array(  "name" => 'MANGUSU'));
        Barangay::create(array(  "name" => 'MANICAHAN'));
        Barangay::create(array(  "name" => 'MARIKI'));
        Barangay::create(array(  "name" => 'MERCEDES'));
        Barangay::create(array(  "name" => 'MUTI'));
        Barangay::create(array(  "name" => 'PAMUCUTAN'));
        Barangay::create(array(  "name" => 'PANGAPUYAN'));
        Barangay::create(array(  "name" => 'PANUBIGAN'));
        Barangay::create(array(  "name" => 'PASILMANTA'));
        Barangay::create(array(  "name" => 'PASONANCA'));
        Barangay::create(array(  "name" => 'PATALON'));
        Barangay::create(array(  "name" => 'PUTIK'));
        Barangay::create(array(  "name" => 'QUINIPUT'));
        Barangay::create(array(  "name" => 'RECODO'));
        Barangay::create(array(  "name" => 'RIO HONDO'));
        Barangay::create(array(  "name" => 'VITALI'));
        Barangay::create(array(  "name" => 'SALAAN'));
        Barangay::create(array(  "name" => 'SANGALI'));
        Barangay::create(array(  "name" => 'SAN JOSE CAWA-CAWA'));
        Barangay::create(array(  "name" => 'SAN JOSE GUSU'));
        Barangay::create(array(  "name" => 'MANALIPA'));
        Barangay::create(array(  "name" => 'SAN ROQUE'));
        Barangay::create(array(  "name" => 'SIBULAO'));
        Barangay::create(array(  "name" => 'SINUBONG'));
        Barangay::create(array(  "name" => 'SINUNUC'));
        Barangay::create(array(  "name" => 'STA BARBARA'));
        Barangay::create(array(  "name" => 'STA CATALINA'));
        Barangay::create(array(  "name" => 'STA MARIA'));
        Barangay::create(array(  "name" => 'STO NIÑO'));
        Barangay::create(array(  "name" => 'TAGASILAY'));
        Barangay::create(array(  "name" => 'TAGUITI'));
        Barangay::create(array(  "name" => 'TALABAAN'));
        Barangay::create(array(  "name" => 'TALISAYAN'));
        Barangay::create(array(  "name" => 'TALON-TALON'));
        Barangay::create(array(  "name" => 'TALUKSANGAY'));
        Barangay::create(array(  "name" => 'TETUAN'));
        Barangay::create(array(  "name" => 'TICTABON'));
        Barangay::create(array(  "name" => 'TICTAPUL'));
        Barangay::create(array(  "name" => 'TIGBALABAG'));
        Barangay::create(array(  "name" => 'TOLOSA'));
        Barangay::create(array(  "name" => 'TUGBUNGAN'));
        Barangay::create(array(  "name" => 'TULUNGATUNG'));
        Barangay::create(array(  "name" => 'TUMAGA'));
        Barangay::create(array(  "name" => 'TUMALUTAP'));
        Barangay::create(array(  "name" => 'LICOMO'));
        Barangay::create(array(  "name" => 'ZAMBOWOOD'));
        Barangay::create(array(  "name" => 'VICTORIA'));
        Barangay::create(array(  "name" => 'LICOMO'));
        Barangay::create(array(  "name" => 'ZAMBOWOOD'));
        Barangay::create(array(  "name" => 'VICTORIA'));
        Barangay::create(array(  "name" => 'PASOBOLONG'));
        Barangay::create(array(  "name" => 'KASANYANGAN'));
     
    }
}
